project:
  type: website
  output-dir: docs

website:
  title: "RSSPtho's Blog"
  site-url: https://www.myblogexample.io
  description: "生信中转站"
  navbar:
    right:
      - icon: rss
        href: index.xml
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: Sandstone
    css: Sandstone.css



