sidebar:
#   # 第一个siderbar的style设置会传递到后面的
  - id: Book2
    style: floating
    background: light
    collapse-level: 3
    contents:
      # 想用id，这里第一个不能用`text`
      - Books/Book2/index.qmd
      - section: "Section 1"
        contents:
          - Books/Book2/test1.qmd
          - Books/Book2/test2.qmd